/** app mutation */
export const SET_APP_USER_PREFERENCES = 'SET_APP_USER_PREFERENCES'
export const SET_IS_MOBILE = 'SET_IS_MOBILE'
export const SET_SIDEBAR_COLLAPSE = 'SET_SIDEBAR_COLLAPSE'
export const SET_SIDETAB_COLLAPSE = 'SET_SIDETAB_COLLAPSE'
export const SET_HANDOVER_MESSAGE_SORT = 'SET_HANDOVER_MESSAGE_SORT'
export const SET_IS_URL_PUBLIC = 'SET_IS_URL_PUBLIC'
export const SET_BULLETIN_EDITABLE = 'SET_BULLETIN_EDITABLE'
export const SET_ENUM_REFS = 'SET_ENUM_REFS'
export const SET_PANEL_COMPONENTS = 'SET_PANEL_COMPONENTS'
export const SET_PAGE_COMPONENTS = 'SET_PAGE_COMPONENTS'
export const SET_FONT_SIZE = 'SET_FONT_SIZE'
export const SET_LANG = 'SET_LANG'
export const SET_ALL_EMPLOYEES = 'SET_ALL_EMPLOYEES'
export const SET_PAGE_SIZE_SELECT = 'SET_PAGE_SIZE_SELECT'

/** bulletinSummaries mutation */
export const SET_BULLETIN_SUMMARIES = 'SET_BULLETIN_SUMMARIES'
export const SET_HASHMAP = 'SET_HASHMAP'
export const SET_UNREAD_COUNT = 'SET_UNREAD_COUNT'

/** menu mutation */
export const SET_MENU_LIST = 'SET_MENU_LIST'

/** panels mutation */
export const ADD_PANEL = 'ADD_PANEL'
export const HIDE_PANEL = 'HIDE_PANEL'
export const CLOSE_PANEL = 'CLOSE_PANEL'
export const CLOSE_HIDDEN_PANELS = 'CLOSE_HIDDEN_PANELS'

/** tabs mutation */
export const SET_TAB_USER_PREFERENCES = 'SET_TAB_USER_PREFERENCES'
export const SET_TABS = 'SET_TABS'
export const CLOSE_TAB = 'CLOSE_TAB'
export const SORT_TABS = 'SORT_TABS'
export const SET_TAB_STATUS = 'SET_TAB_STATUS'
export const SET_RECORD_TABS = 'SET_RECORD_TABS'
export const UPDATE_TAB = 'UPDATE_TAB'

/** options mutation */
export const SET_BULLETIN_CLASS_LIST = 'SET_BULLETIN_CLASS_LIST'
export const SET_HANDOVER_TYPE_LIST = 'SET_HANDOVER_TYPE_LIST'
export const SET_HANDOVER_TAG_LIST = 'SET_HANDOVER_TAG_LIST'
export const SET_CONTRACTOR_LIST = 'SET_CONTRACTOR_LIST'
export const SET_SITE_PLATFORM_LIST = 'SET_SITE_PLATFORM_LIST'
export const SET_SITE_TYPE_LIST = 'SET_SITE_TYPE_LIST'
export const SET_SITE_PURPOSE_LIST = 'SET_SITE_PURPOSE_LIST'
